name: pcrunfixedthisl0l
author: Disclearing(i did this in 10 seconds and this kid did what ever he did I just merged this shit)
description: fuck anyone who thinks i skid
version: 1.0
main: xyz.disclearing.pp.main
commands:
    skid:
